server:
  port: 8080
  context-path: /springboot
  
  
spring:
   mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
   datasource:
      url: jdbc:mysql://localhost:3306/project
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root!@#
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
   dubbo:
     application:
       id: project-dubbo-provider
       name: project-dubbo-provider
     registry:
       address: zookeeper://localhost:2181
     server: true
     protocol:
       name: dubbo
       port: 20880
  #redis配置
   redis:
     host: 127.0.0.1
     port: 6379
     # REDIS (RedisProperties)
     # Redis数据库索引（默认为0）
     database: 0
     # Redis服务器连接密码（默认为空）
     password:
     # 连接池最大连接数（使用负值表示没有限制）
     # 连接超时时间（毫秒）
     timeout: 0
     pool:
       max-active: 8
       # 连接池最大阻塞等待时间（使用负值表示没有限制）
       max-wait: -1
       # 连接池中的最大空闲连接
       max-idle: 8
       # 连接池中的最小空闲连接
       min-idle: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.entry 

rocketmq:
  producer:
    #该应用是否启用生产者
    isOnOff: on
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: springbootProject
    #mq的nameserver地址
    namesrvAddr: 192.168.2.103:9876
    #消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    #发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    #发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2


